server {
    listen 80;  # The port that Nginx will listen on
    server_name localhost;  # Server name

    root /usr/share/nginx/html/public;  # The public directory of Laravel

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;  # Tries to serve static files or redirects to index.php
    }

    location ~ \.php$ {
        include fastcgi_params;  # Includes FastCGI parameters
        fastcgi_pass tasksun-backend:9000;  # PHP-FPM listens on this port
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;  # Defines the path to the PHP script
    }

    location ~ /\.ht {
        deny all;  # Denies access to .htaccess files
    }
}
